-- FULL DATA FROM SPA (CORRECTED VERSION)
-- ACCOMMODATIONS
INSERT INTO accommodations (name, type, location, description, address, phone, email, website)
VALUES
('Ramada Resort Port Vila', 'Waterfront Resort', 'Port Vila, Efate',
'Modern waterfront resort offering lagoon-view apartments, spa and marina access',
'First Lagoon, Paray, Port Vila, Vanuatu',
'+678 28000',
'reservations@ramadaresort.com.vu',
'https://ramadaresort.com.vu'),

('Warwick Le Lagon Vanuatu', 'Beachfront Resort', 'Port Vila, Efate',
'Large beachfront resort with spa, pools and conference facilities',
'Erakor Lagoon, Port Vila, Vanuatu',
'+678 22313',
'reservations.vanuatu@warwickhotels.com',
'https://www.warwickhotels.com/le-lagon-vanuatu'),

('Breakas Beach Resort', 'Adults-only Beach Resort', 'Port Vila, Efate',
'Adults-only beachfront resort featuring traditional island-style bungalows',
'Pango Road, Port Vila, Vanuatu',
'+678 23670',
'reservations@breakas.com',
'https://breakas.com'),

('Holiday Inn Resort Vanuatu', 'Family Resort', 'Port Vila, Efate',
'Family-friendly resort with lagoon views, golf course and kids club',
'Tassiriki Park, Port Vila',
'+678 22100',
'reservations.hivanuatu@ihg.com',
'https://www.ihg.com/holidayinnresorts/vanuatu'),

('Grand Hotel and Casino Port Vila', 'Luxury Hotel', 'Port Vila, Efate',
'Harbourfront luxury hotel with casino and business facilities',
'Kumul Highway, Port Vila',
'+678 33500',
'reservations@grandvanuatu.com',
'https://www.grandvanuatu.com'),

('The Melanesian Port Vila', 'Hotel', 'Port Vila, Efate',
'Hotel with cultural shows, pool and traditional kava bar',
'Rue Picarde, Port Vila',
'+678 22285',
'reservations@melanesian.com.vu',
'https://www.melanesian.com.vu'),

('Erakor Island Resort', 'Private Island Resort', 'Erakor Island, Efate',
'Island resort with beachfront bungalows and water sports',
'Erakor Island, Port Vila',
'+678 26983',
'reservations@erakorislandresort.com',
'https://www.erakorislandresort.com'),

('The Havannah Vanuatu', 'Luxury Adults-only Resort', 'Efate',
'Luxury resort known for honeymoons and private relaxation',
'Havannah Harbour, Efate',
'+678 27600',
'stay@thehavannah.com',
'https://www.thehavannah.com'),

('Tamanu on the Beach', 'Boutique Beach Resort', 'North Efate',
'Luxury beachfront villas with spa and fine dining',
'White Sands Road, North Efate',
'+678 22521',
'reservations@tamanuonthebeach.com',
'https://www.tamanuonthebeach.com'),

('Nasama Resort', 'Resort', 'Port Vila, Efate',
'Relaxed resort with ocean views and self-contained apartments',
'Pango Road, Port Vila',
'+678 27200',
'reservations@nasamaresort.com',
'https://www.nasamaresort.com');

-- CAR RENTALS (CLEAN + CORRECTED)
INSERT INTO car_rentals (name, services, location, address, phone, email, website)
VALUES
('World Car Rentals Vanuatu',
'Compact cars, SUVs, 4WD vehicles, airport transfers',
'Port Vila, Efate',
'Kumul Highway, Nambatu Area, Port Vila, Vanuatu',
'+678 26515',
'bookings@vanuaturentalcars.com',
'https://www.vanuaturentalcars.com'),

('Europcar Vanuatu',
'Daily and long-term car rental services',
'Port Vila, Efate',
'Lini Highway, Port Vila, Vanuatu',
'+678 26517',
'europcar@vanuatu.com.vu',
'https://www.europcar.vu'),

('Avis Vanuatu',
'Economy cars, SUVs, rental vehicles',
'Port Vila, Efate',
'Kumul Highway, Port Vila',
'+678 35335',
NULL,
'https://avisvanuatu.com'),

('Hertz Car Rental',
'Short and long-term rentals',
'Port Vila, Efate',
'Lini Highway, Port Vila',
'+678 22468',
NULL,
'https://www.hertz.com'),

('Budget Vanuatu',
'Car and truck rentals',
'Port Vila, Efate',
'Tagabe Area, Port Vila',
'+678 25444',
NULL,
'http://www.rentalcarsvanuatu.com'),

('On Wheels Vanuatu',
'Cars, scooters, quad bikes',
'Port Vila, Efate',
'Lini Highway, Port Vila',
'+678 7771646',
NULL,
'https://bookmevanuatu.com'),

('Go2Rent',
'Small cars and SUV rentals',
'Port Vila, Efate',
'Kumul Highway, Nambatu',
'+678 7771646',
NULL,
'http://go2rent.com.vu'),

('Global Drive Car Rentals',
'SUVs and 4WD vehicles',
'Port Vila, Efate',
'Kumul Highway, Port Vila',
'+678 5273180',
NULL,
'https://www.globaldrivecarrentals.com'),

('Santo Tropical Car Rentals',
'Local rentals and airport delivery',
'Luganville, Santo',
'Luganville, Espiritu Santo',
'+678 5634918',
'santotropicalrental@gmail.com',
'https://www.santorentalcars.com'),

('Pacific Car Hire Santo',
'4WD and utility vehicle rentals',
'Luganville, Santo',
'Cook Street, Luganville',
'+678 36036',
'santoislandcarrental@gmail.com',
'https://pacificcarhire.com'),

('Santo Car Hire',
'Budget and SUV rentals',
'Luganville, Santo',
'Luganville, Espiritu Santo',
'+678 7770888',
'santocarhire@gmail.com',
'https://carhire.vu'),

('Wanderlust Rentals & Tours',
'Car rentals and guided tours',
'Luganville, Santo',
'Luganville, Espiritu Santo',
'+678 7658547',
'info@wanderlust.vu',
'https://wanderlust.vu');


-- TOUR OPERATORS (CLEAN + CORRECTED)
INSERT INTO tour_operators (name, services, location, phone, email, website)
VALUES
('Vanuatu Ecotours',
'Eco tours, cultural experiences, outer island adventures',
'Port Vila, Efate',
'+678 5403506',
'info@vanuatuecotours.com',
'https://vanuatuecotours.com'),

('Atmosphere Tours Vanuatu',
'Island tours, cruise excursions and transfers',
'Port Vila, Efate',
'+678 27870',
'office@atmospheretours.com',
'https://www.atmospheretours.com'),

('Evergreen Tours Vanuatu',
'Sightseeing tours, snorkelling trips, transfers',
'Port Vila, Efate',
'+678 23050',
NULL,
NULL),

('Nature Tours Vanuatu',
'Nature exploration, river tours and cultural experiences',
'Port Vila, Efate',
'+678 7790351',
NULL,
NULL),

('South Pacific Tours (SPT)',
'Cruise tours and Efate sightseeing',
'Port Vila, Efate',
'+678 26559',
NULL,
NULL),

('Off Road Adventures Vanuatu',
'Buggy tours and jungle exploration',
'Port Vila, Efate',
'+678 25479',
NULL,
NULL),

('Vila Hope Tours & Transfers',
'Private transport and airport transfers',
'Port Vila, Efate',
'+678 5444455',
NULL,
NULL),

('Bountiful Tours & Transfers',
'Local tours and private transfers',
'Port Vila, Efate',
'+678 7712159',
NULL,
NULL),

('Rarru Rentapao River Tours',
'River adventure tours and jungle walks',
'Efate',
'+678 5551007',
NULL,
NULL),

('Lelepa Island Tours',
'Island visits and cultural tours',
'Port Vila, Efate',
'+678 7763516',
NULL,
NULL),

('Santo Heritage Tours',
'WWII historical tours and island sightseeing',
'Espiritu Santo',
'+678 7740968',
NULL,
NULL),

('Paradise Tours Santo',
'Private tours and group excursions',
'Espiritu Santo',
'+678 7747159',
NULL,
NULL),

('Mystery Island Tours',
'Cruise-based island tours',
'Aneityum',
'+678 5434562',
NULL,
NULL);