name: Booking System CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Start server
        run: |
          node api.js &
      
      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Test server
        run: curl -f http://localhost:3000