name: CI Pipeline
 staging

main
on:
  push:
    branches:
      - '**'
 staging


 main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 staging

main
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
staging

      - name: Install dependencies
        run: |
          npm install
          cd back-end
          npm install

      - name: Run app
        run: |
          cd back-end
          node index.js &

      - name: Wait for server
        run: sleep 3


      - name: Install dependencies
        run: |
          npm install
          cd back-end
          npm install
      - name: Run app
        run: |
          cd back-end
          node index.js &
      - name: Wait for server
        run: sleep 3
 main
      - name: Test API
        run: curl -f http://localhost:5000/
        
      - name: Stop server
 staging
        run: pkill node

        run: pkill node
 main
